- name: "Update Running Ursula"
  hosts: "{{ play_hosts }}"
  remote_user: "{{default_user}}"
  gather_facts: no
  tasks:

    - name: Keep disk space clean by pruning unneeded docker debris
      become: yes
      docker_prune:
        containers: yes
        images: yes
        networks: yes
        builder_cache: yes

    - name: "pull {{ nucypher_image | default('nucypher/nucypher:latest') }}"
      become: yes
      docker_image:
        name: "{{ nucypher_image | default('nucypher/nucypher:latest') }}"
        source: pull
        force_source: yes

- import_playbook: stop_containers.yml
- import_playbook: run_geth.yml
  when: DECENTRALIZED is not undefined and DECENTRALIZED
- import_playbook: run_ursula.yml
